# Generated by Django 5.2.8 on 2025-11-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'surah_number')},
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='surah_number',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='ayah_number',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='updated_at',
        ),
    ]
