# Generated by Django 5.2.8 on 2025-11-27 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_bookmark_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
